### ISSUE TITLE
Repoman's stuck if there's an error enabling a specific source [20.10 Upgrade]

### ISSUE THREAD

**Issue by MikhailTNY** [pop-os/pop#1322]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 ```
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Repoman: 
```
repoman:
  Installed: 2.0.0~1603294431~20.10~1555cb3
  Candidate: 2.0.0~1603294431~20.10~1555cb3
  Version table:
 *** 2.0.0~1603294431~20.10~1555cb3 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```
**Issue/Bug Description:**

After updating to 20.10, editing to enable a specific source in Pop Shop's extra source doesn't work at all. 

In console: 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 166, in on_edit_button_clicked
    self.do_edit(repo_name)
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 188, in do_edit
    dialog.source.save_to_disk()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 144, in save_to_disk
    source_output = self.make_deblines()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 175, in make_deblines
    toprint += f'{out_binary.make_debline()}\n'
  File "/usr/lib/python3/dist-packages/repolib/source.py", line 211, in make_debline
    line += self._get_options()
  File "/usr/lib/python3/dist-packages/repolib/source.py", line 427, in _get_options
    opt_str += f'{self.outoptions_d[key]}={self.options[key].replace(" ", ",")} '
KeyError: 'signed-by'


```

**Steps to reproduce (if you know):**

The source was added as such on 20.04: 

>  echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password.gpg] https://downloads.1password.com/linux/debian edge main' | sudo tee /etc/apt/sources.list.d/1password.list

After upgrade, open Pop Shop, go to Settings > Extra Source, find the 1Password source and edit to enable it. After that, you cannot leave the view, it can't be saved nor cancelled. 

![image](https://user-images.githubusercontent.com/370953/97087610-302c4f80-15e0-11eb-9743-df7094d355e4.png)

**Expected behavior:**

I expected to see the error on the view and be able to cancel it completely. 

**Other Notes:**

**Comment by bartlebee13** [comment]
I don't know if this is the same or similar issue but I have an issue with repoman as well after upgrading to 20.10 which I believe is preventing the Pop! Store from working properly.

```
(repoman:28797): Gtk-CRITICAL **: 21:33:06.593: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 37, in do_activate
    self.win = Window()
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 36, in __init__
    self.stack = Stack(self)
  File "/usr/lib/python3/dist-packages/repoman/stack.py", line 58, in __init__
    self.list_all = List(self)
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 42, in __init__
    self.sp = SoftwareProperties()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 111, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 605, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Pop/groovy
```

**aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Pop/groovy**
