### ISSUE TITLE
Suggestion: On the website have a guide for setting up on Chromebooks

### ISSUE THREAD

**Issue by justingolden21** [pop-os/pop#1430]
*Went through the whole thing at https://chat.pop-os.org/ to create an account for that mail service and user, pass, verify, etc, just for it to say "No teams are available to join. Please create a new team or ask your administrator for an invite." when I get there, so I am completely incapable of going there, my apologies.*

Just wanted to say that since Pop OS seems very popular with Chromebook owners and is often suggested to new users, an article / step by step guide on your website would be the perfect way to pull in more users and make it easier for them to start. Just a quick setup guide somewhere on https://pop.system76.com/ would be perfect. (I see that this is the OS repo, but I was unable to find a website repo after searching for a bit; if there is one please point me in the right direction.)

I for one had some issues, even when following this guide: https://chromeunboxed.com/installing-pop-os-chromebook-virtual-machine-crostini-linux-vm/ and virtual machine manager ended up giving me:

```
Unable to connect to libvert qemu:///system.

authentication unavailable: no polkit agent available to authenticate action 'org.libvert.unix.manage'

Would you still like to remember this connection?
```

I then tried following https://askubuntu.com/a/736623/1155582  but got stuck on step 2 with `usermod: group 'libvirtd' does not exist ` before finally finding this: https://www.reddit.com/r/kvm/comments/ihhdol/qemukvm_not_connected/g3089gv?utm_source=share&utm_medium=web2x&context=3 and continuing onwards... Despite just a few simple steps, it took me HOURS of searching dozens if not hundreds of websites, articles, forums, and videos, just to get Pop setup, and I'm at least a tech savvy user.

The average person looking to get Pop on their Chromebook would probably be far more hindered and likely give up, but a simple step by step guide from Pop would provide the assistance necessary to get Pop up and running quickly. The tradeoff for writing an article in a few hours and getting potentially hundreds or thousands of new users seems worth it to me, so I wanted to share this suggestion. Thanks, and I'm looking forward to using Pop : )

Side note: Wondering why this is taking over a half hour on my brand new laptop when I gave Pop 4gb RAM, 10gb storage, and both cores.

**Comment by justingolden21** [comment]
After a total of an hour and ten minutes, I was unable to get Pop setup:

![Screenshot 2020-12-07 at 8 23 31 PM](https://user-images.githubusercontent.com/30274440/101439825-3e9da480-38ca-11eb-8dde-9b1b4c845034.png)

**Comment by justingolden21** [comment]
50 minutes later it got to 70%, hung for a while, and then got to this again. I cannot seem to access the directory mentioned in the message as well... If anyone has any advice on this please let me know. It's been a huge headache getting Pop set up, and I have a feeling it's not Pop's fault.

**Comment by justingolden21** [comment]
It's been doing this for over 20min:

![image](https://user-images.githubusercontent.com/30274440/101444563-9c36ee80-38d4-11eb-8f00-944912fb3578.png)

**Comment by justingolden21** [comment]
Even shutting it down gave me an error:
```
Error shutting down domain: Requested operation is not valid: domain is not running

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 111, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/libvirtobject.py", line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/domain.py", line 1371, in shutdown
    self._backend.shutdown()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 2496, in shutdown
    if ret == -1: raise libvirtError ('virDomainShutdown() failed', dom=self)
libvirt.libvirtError: Requested operation is not valid: domain is not running
```

**Comment by justingolden21** [comment]
I think I'm just going to powerwash my chromebook and give up on this... I've been at this for many hours now, tried installing the OS from scratch three times, after closing it got to the "booting from hard disk" screen for over 20min three times, restarted the computer and updated it and tried again and can't get past "booting from hard disk".

I have a "hp chromebook 14c-ca0053dx", here are the details on the HP store: https://www8.hp.com/us/en/laptops/product-details/34370440 it's not even listed under Gallium's hardware compatibility list: https://wiki.galliumos.org/Hardware_Compatibility

**Comment by justingolden21** [comment]
After some more research, it seems maybe my chromebook is too new for Ubuntu support? If someone has any info on this please let me know. Also I apologize for the tangent: my suggestion was just to add a simple guide to the website for setting up Pop OS on chrome OS. I made that suggestion when I thought I had Pop working, and since then I realized that Pop still isn't working for me, but my original suggestion still stands of course : )

**Comment by justingolden21** [comment]
Restarted the computer, virtual desktop manager, killed the instance and created a new virtual machine, followed through installation steps again, got to 70% again and then the same error. I realized there's a little "show console" button on the left, so hoping the output may help someone:

![image](https://user-images.githubusercontent.com/30274440/101554762-1fefea00-396c-11eb-8c76-816d97c50a96.png)

Above is the bottom of the logger, here is the place where the very long list of errors first started:

![image](https://user-images.githubusercontent.com/30274440/101554936-76f5bf00-396c-11eb-832c-c45b324c03cb.png)

Not sure if it's a space issue or not, as I gave it 10gb which should be plenty for a linux OS from what I know, but then again I don't know a lot.

**Comment by jacobgkau** [comment]
`No space left on device` does sound like a space issue.

> I gave it 10gb which should be plenty for a linux OS from what I know

You gave 10GB to what, the root partition? On a relatively fresh Pop install, I'm using 14GB on the root partition according to `df -h`. I would try again with at least 20GB, or 30GB if you want to be able to comfortably install more packages and put files on the system. If you really need to conserve space, you could bump it up 1GB at a time until you stop getting that particular error message.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by justingolden21** [comment]
Thank you for the reply. I figured that 10gb was enough because the OS itself is only about 2.5 I believe. I actually realized that I can install debian apps on chrome os itself so I don't think I'll be running a VM then, but I appreciate the help.

**Comment by ids1024** [comment]
We're probably not interested in providing official guides for things this hardware specific. But it could be cool if someone wants to write a guide. Perhaps the (community run) wiki on https://pop-planet.info/ could be a good place for something like that.

**Comment by justingolden21** [comment]
That makes sense. That's a good idea to put it in the wiki. Maybe a CTA button on the main page somewhere linking to the wiki guide, with button text along the lines of "Setting up Pop OS on a Chromebook"
