### ISSUE TITLE
Cannot upgrade from 20.04 to 20.10

### ISSUE THREAD

**Issue by vladp** [pop-os/pop#1537]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Cannot upgrade PopOS 20.10 from 20.04.
Started this weekend, it seems that upgrade was installed but then was automatically reversing.
At the end I am stuck with this error message  ' failed to fetch apt URIs to fetch

I had followed the [System 76 blog](https://support.system76.com/articles/upgrade-pop/) to upgrade.

All steps are done, no extra packages to upgrades:
```

root@w520r16-lin-ssd:~# sudo apt full-upgrade | tee ~/upgrade.log                    
                                                                                     
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.      
                                                                                     
Reading package lists...                                                             
Building dependency tree...                                                          
Reading state information...                                                         
Calculating upgrade...                                                               
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.                       
root@w520r16-lin-ssd:~#                                                              
```

The last suggestion was to 'run do-release-upgrade'
That resulted in a bunch of errors:

```
Reading package lists... Done                                                                                    
Building dependency tree                                                                                         
Reading state information... Done                                                                                
Hit http://us.archive.ubuntu.com/ubuntu focal InRelease                                                          
Get:1 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                                       
Hit http://ppa.launchpad.net/system76/pop/ubuntu focal InRelease                                                 
Hit http://apt.pop-os.org/proprietary focal InRelease                                                            
Hit http://us.archive.ubuntu.com/ubuntu focal-security InRelease                                                 
Get:2 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]                                     
Hit http://apt.pop-os.org/proprietary groovy InRelease                                                           
Hit http://us.archive.ubuntu.com/ubuntu groovy InRelease                                                         
Hit http://us.archive.ubuntu.com/ubuntu groovy-security InRelease                                                
Get:3 http://us.archive.ubuntu.com/ubuntu groovy-updates InRelease [115 kB]                                      
Get:4 http://us.archive.ubuntu.com/ubuntu groovy-backports InRelease [101 kB]                                    
Fetched 430 kB in 0s (0 B/s)                                                                                     
Reading package lists... Done                                                                                    
Building dependency tree                                                                                         
Reading state information... Done                                                                                
                                                                                                                 
Updating repository information                                                                                  
                                                                                                                 
Traceback (most recent call last):                                                                               
  File "/tmp/ubuntu-release-upgrader-16zlkkn4/groovy", line 8, in <module>                                       
    sys.exit(main())                                                                                             
  File "/tmp/ubuntu-release-upgrader-16zlkkn4/DistUpgrade/DistUpgradeMain.py", line 238, in main                 
    if app.run():                                                                                                
  File "/tmp/ubuntu-release-upgrader-16zlkkn4/DistUpgrade/DistUpgradeController.py", line 2089, in run           
    return self.fullUpgrade()                                                                                    
  File "/tmp/ubuntu-release-upgrader-16zlkkn4/DistUpgrade/DistUpgradeController.py", line 1932, in fullUpgrade   
    if not self.updateSourcesList():                                                                             
  File "/tmp/ubuntu-release-upgrader-16zlkkn4/DistUpgrade/DistUpgradeController.py", line 801, in updateSourcesLi
st                                                                                                               
    self.sources = SourcesList(matcherPath=self.datadir)                                                         
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 273, in __init__                         
    self.matcher = SourceEntryMatcher(matcherPath)                                                               
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 470, in __init__                         
    dist = DistInfo(base_dir=matcherPath)                                                                        
  File "/usr/lib/python3/dist-packages/aptsources/distinfo.py", line 184, in __init__                            
    with open(dist_fname) as dist_file:                                                                          
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ubuntu-release-upgrader-16zlkkn4/Pop.info'         
Error in sys.excepthook:                                                                                         
Traceback (most recent call last):                                                                               
  File "/usr/lib/python3/dist-packages/problem_report.py", line 477, in add_to_existing                          
    self.write(f)                                                                                                
  File "/usr/lib/python3/dist-packages/problem_report.py", line 430, in write                                    
    block = f.read(1048576)                                                                                      
  File "/usr/lib/python3.8/codecs.py", line 322, in decode                                                       
    (result, consumed) = self._buffer_decode(data, self.errors, final)                                           
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte                       
                                                                                                                 
Original exception was:                                                                                          
Traceback (most recent call last):                                                                               
  File "/tmp/ubuntu-release-upgrader-16zlkkn4/groovy", line 8, in <module>                                       
    sys.exit(main())                                                                                             
  File "/tmp/ubuntu-release-upgrader-16zlkkn4/DistUpgrade/DistUpgradeMain.py", line 238, in main                 
    if app.run():                                                                                                
  File "/tmp/ubuntu-release-upgrader-16zlkkn4/DistUpgrade/DistUpgradeController.py", line 2089, in run           
    return self.fullUpgrade()                                                                                    
  File "/tmp/ubuntu-release-upgrader-16zlkkn4/DistUpgrade/DistUpgradeController.py", line 1932, in fullUpgrade   
    if not self.updateSourcesList():                                                                             
  File "/tmp/ubuntu-release-upgrader-16zlkkn4/DistUpgrade/DistUpgradeController.py", line 801, in updateSourcesLi
st                                                                                                               
    self.sources = SourcesList(matcherPath=self.datadir)                                                         
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 273, in __init__                         
    self.matcher = SourceEntryMatcher(matcherPath)                                                               
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 470, in __init__                         
    dist = DistInfo(base_dir=matcherPath)                                                                        
  File "/usr/lib/python3/dist-packages/aptsources/distinfo.py", line 184, in __init__                            
    with open(dist_fname) as dist_file:                                                                          
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ubuntu-release-upgrader-16zlkkn4/Pop.info'         
root@mypc:~#                                                                                          


```

**Steps to reproduce (if you know):**

root@mypc:~# pop-upgrade release upgrade                                                           
checking if pop-upgrade requires an update                                                                    
Current Release: 20.04                                                                                        
Upgrading to: 20.10                                                                                           
New version available: 10                                                                                     
Event: updating package lists                                                                                 
Event: fetching updated packages for the current release                                                      
Release upgrade status: release upgrade aborted: failed to fetch apt URIs to fetch                            
pop-upgrade: dbus client error                                                                                
  caused by: calling ReleaseUpgradeFinalize method failed                                                     
  caused by: "release upgrade cannot be finalized, because a release upgrade was not performed"               
root@mypc:~#                                                                                       

**Expected behavior:**

Release should be upgraded

**Other Notes:**
I am also getting this error (although this is first time I was trying this command, I saw it in the upgrade blog) :

root@mypc:~# sudo apt install pop-desktop                            
Reading package lists... Done                                                   
Building dependency tree                                                        
Reading state information... Done                                               
Some packages could not be installed. This may mean that you have               
requested an impossible situation or if you are using the unstable              
distribution that some required packages have not yet been created              
or been moved out of Incoming.                                                  
The following information may help to resolve the situation:                    
                                                                                
The following packages have unmet dependencies:                                 
 pop-desktop : Depends: gvfs-bin                                                
               Depends: gdm3 but it is not installable                          
               Recommends: gnome-contacts but it is not installable             
               Recommends: io.elementary.sideload but it is not installable     
E: Unable to correct problems, you have held broken packages.

**Comment by bflanagin** [comment]
Thanks for your report @vladp we've been monitoring this issue since it started and have a moved everyone to the same issue found here: https://github.com/pop-os/upgrade/issues/138 If you could follow along there and add your experience and the files I requested from the others there it would benefit the bug hunt.
