### ISSUE TITLE
do-release-upgrade fails to update Pop!_OS 20.04 LTS

### ISSUE THREAD

**Issue by morgankevinj** [pop-os/pop#1545]
**Distribution (run `cat /etc/os-release`):**
root@pop-os:~# cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
do-release-upgrade fails to update

**Steps to reproduce (if you know):**
root@pop-os:~# do-release-upgrade 
Checking for a new Ubuntu release
Get:1 Upgrade tool signature [819 B]                                                                                                             
Get:2 Upgrade tool [1,341 kB]                                                                                                                    
Fetched 1,342 kB in 0s (0 B/s)                                                                                                                   
authenticate 'groovy.tar.gz' against 'groovy.tar.gz.gpg' 
extracting 'groovy.tar.gz'

Reading cache

Checking package manager
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Hit http://us.archive.ubuntu.com/ubuntu groovy InRelease                                                                                         
Hit http://us.archive.ubuntu.com/ubuntu groovy-security InRelease                                                                                
Hit http://us.archive.ubuntu.com/ubuntu groovy-updates InRelease                                                                                 
Hit http://us.archive.ubuntu.com/ubuntu groovy-backports InRelease                                                                               
Hit http://apt.pop-os.org/proprietary focal InRelease                                                                                            
Hit http://ppa.launchpad.net/system76/pop/ubuntu groovy InRelease                                                                                
Hit https://brave-browser-apt-release.s3.brave.com stable InRelease                                                                              
Hit http://archive.canonical.com focal InRelease                                                                                                 
Hit http://packages.microsoft.com/repos/edge stable InRelease                                                                                    
Hit http://apt.pop-os.org/proprietary groovy InRelease                                                                                           
Hit http://ppa.launchpad.net/system76/pop/ubuntu focal InRelease                                                                                 
Hit https://repos.azul.com/zulu/deb stable InRelease                                                                                             
Hit https://iweb.dl.sourceforge.net/project/ubuntuzilla/mozilla/apt all InRelease                                                                
Fetched 0 B in 0s (0 B/s)                                                                                                                        
Reading package lists... Done    
Building dependency tree          
Reading state information... Done

Updating repository information

Traceback (most recent call last):
  File "/tmp/user/0/ubuntu-release-upgrader-qofomyvd/groovy", line 8, in <module>
    sys.exit(main())
  File "/tmp/user/0/ubuntu-release-upgrader-qofomyvd/DistUpgrade/DistUpgradeMain.py", line 238, in main
    if app.run():
  File "/tmp/user/0/ubuntu-release-upgrader-qofomyvd/DistUpgrade/DistUpgradeController.py", line 2089, in run
    return self.fullUpgrade()
  File "/tmp/user/0/ubuntu-release-upgrader-qofomyvd/DistUpgrade/DistUpgradeController.py", line 1932, in fullUpgrade
    if not self.updateSourcesList():
  File "/tmp/user/0/ubuntu-release-upgrader-qofomyvd/DistUpgrade/DistUpgradeController.py", line 801, in updateSourcesList
    self.sources = SourcesList(matcherPath=self.datadir)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 273, in __init__
    self.matcher = SourceEntryMatcher(matcherPath)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 470, in __init__
    dist = DistInfo(base_dir=matcherPath)
  File "/usr/lib/python3/dist-packages/aptsources/distinfo.py", line 184, in __init__
    with open(dist_fname) as dist_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/user/0/ubuntu-release-upgrader-qofomyvd/Pop.info'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/problem_report.py", line 477, in add_to_existing
    self.write(f)
  File "/usr/lib/python3/dist-packages/problem_report.py", line 430, in write
    block = f.read(1048576)
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

Original exception was:
Traceback (most recent call last):
  File "/tmp/user/0/ubuntu-release-upgrader-qofomyvd/groovy", line 8, in <module>
    sys.exit(main())
  File "/tmp/user/0/ubuntu-release-upgrader-qofomyvd/DistUpgrade/DistUpgradeMain.py", line 238, in main
    if app.run():
  File "/tmp/user/0/ubuntu-release-upgrader-qofomyvd/DistUpgrade/DistUpgradeController.py", line 2089, in run
    return self.fullUpgrade()
  File "/tmp/user/0/ubuntu-release-upgrader-qofomyvd/DistUpgrade/DistUpgradeController.py", line 1932, in fullUpgrade
    if not self.updateSourcesList():
  File "/tmp/user/0/ubuntu-release-upgrader-qofomyvd/DistUpgrade/DistUpgradeController.py", line 801, in updateSourcesList
    self.sources = SourcesList(matcherPath=self.datadir)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 273, in __init__
    self.matcher = SourceEntryMatcher(matcherPath)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 470, in __init__
    dist = DistInfo(base_dir=matcherPath)
  File "/usr/lib/python3/dist-packages/aptsources/distinfo.py", line 184, in __init__
    with open(dist_fname) as dist_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/user/0/ubuntu-release-upgrader-qofomyvd/Pop.info'

**Comment by mmstick** [comment]
Not supported on Pop. Use `pop-upgrade`
