### ISSUE TITLE
Problems after dist upgrade to 21.04, apt, sound, boot... - not find a distribution template for Pop/hirsute

### ISSUE THREAD

**Issue by wellington1993** [pop-os/pop#1727]
**Distribution (run `cat /etc/os-release`):**
```ini
DISTRIB_ID=Pop
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Pop!_OS 21.04"
```

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Grub, Grub2, apt, gnome, alsamixer, pulseaudio

**Issue/Bug Description:**
- `aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Pop/hirsute
`
And...
- Can't boot, I need to select "old kernel" on PC starts
- Can't find Grub or Grb config files do fix the first item
- Sound, USB Headset recognition problems, frequently needs restart.
- Can't manage packages.
- Error in apt:
```python
[wellington]% sudo add-apt-repository ppa:teejee2008/ppa       
[sudo] senha para wellington: 
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 330, in <module>
    addaptrepo = AddAptRepository()
  File "/usr/bin/add-apt-repository", line 35, in __init__
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Pop/hirsute

```

**Steps to reproduce (if you know):**
Update to PoP!_OS 21.04

**Expected behavior:**
- Boot working after update
- Without package update problems
-  What to fiz Grub...

**Other Notes:**
Thanks!

**Comment by wellington1993** [comment]
Trying...
`sudo apt install --reinstall pop-boot pop-default-settings pop-desktop\* pop-gnome-shell-theme pop-gtk-theme pop-session pop-shell-plugin-system76-power pop-shell-shortcuts pop-shell\* pop-fonts pop-transition pop-theme\*`

**Comment by wellington1993** [comment]
When try to update, upgrade packages:
```rust
Os pacotes a seguir possuem dependências não satisfeitas:
 firmware-manager-notify : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 gnome-control-center : Depende: libgdk-pixbuf-2.0-0 (>= 2.25.2) which is a virtual package and is not provided by any available package

                        Depende: libpop-desktop-widget (>= 0.1.0~) mas não é instalável.
 libegl-mesa0 : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                Depende: libx11-xcb1 (>= 2:1.7.0) but 2:1.6.12-1ubuntu0.1 is installed
 libsystemd0 : Pré-Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 libsystemd0:i386 : Pré-Depende: libc6:i386 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 flatpak : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
           Depende: libgdk-pixbuf-2.0-0 (>= 2.22.0) which is a virtual package and is not provided by any available package

 libflatpak0 : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 libpop-upgrade-gtk : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                      Depende: libgdk-pixbuf-2.0-0 (>= 2.22.0) which is a virtual package and is not provided by any available package

 libxatracker2 : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 gnome-settings-daemon : Depende: libgdk-pixbuf-2.0-0 (>= 2.22.0) which is a virtual package and is not provided by any available package

 udev : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 libs76-hidpi-widget : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                       Depende: libgdk-pixbuf-2.0-0 (>= 2.22.0) which is a virtual package and is not provided by any available package

 system76-power : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 libnss-mymachines : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 gdm3 : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
        Depende: libgdk-pixbuf-2.0-0 (>= 2.22.0) which is a virtual package and is not provided by any available package

 linux-headers-5.11.0-7612-generic : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 mozc-utils-gui : Depende: libabsl20200923 (>= 0~20200923-1) which is a virtual package and is not provided by any available package

                  Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                  Depende: libqt5core5a (>= 5.15.1) but 5.14.2+dfsg-6 is installed
                  Depende: libqt5widgets5 (>= 5.15.1) but 5.14.2+dfsg-6 is installed
 libmutter-7-0 : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                 Depende: libgdk-pixbuf-2.0-0 (>= 2.22.0) which is a virtual package and is not provided by any available package

                 Depende: libx11-xcb1 (>= 2:1.7.0) but 2:1.6.12-1ubuntu0.1 is installed
 libudev1 : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 libudev1:i386 : Depende: libc6:i386 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 libgbm1 : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 libgbm1:i386 : Depende: libc6:i386 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 alacritty : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 libgdm1 : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 linux-headers-5.11.0-7614-generic : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 ubuntu-drivers-common : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 libfwupdplugin1 : Depende: libglib2.0-0 (>= 2.67.3) but 2.66.1-2ubuntu0.2 is installed
 mozc-server : Depende: libabsl20200923 (>= 0~20200923-1) which is a virtual package and is not provided by any available package

               Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
               Depende: libprotobuf23 (>= 3.12.4) but 3.12.3-2ubuntu2 is installed
 ibus-mozc : Depende: libabsl20200923 (>= 0~20200923-1) which is a virtual package and is not provided by any available package

             Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
             Depende: libprotobuf23 (>= 3.12.4) but 3.12.3-2ubuntu2 is installed
 libpam-systemd : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 systemd : Pré-Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
           Depende: libgnutls30 (>= 3.7.0) but 3.6.15-4ubuntu2.1 is installed
 libgl1-mesa-dri : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 libgl1-mesa-dri:i386 : Depende: libc6:i386 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 libosmesa6:i386 : Depende: libc6:i386 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 pop-shop : Depende: libgdk-pixbuf-2.0-0 (>= 2.22.0) which is a virtual package and is not provided by any available package

 fwupd : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
         Depende: libgnutls30 (>= 3.7.0) but 3.6.15-4ubuntu2.1 is installed
         Depende: libgusb2 (>= 0.3.5) but 0.3.4-0.2 is installed
         Depende: libtss2-esys-3.0.2-0 (>= 2.3.1) which is a virtual package and is not provided by any available package

 systemd-container : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 libfirmware-manager : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                       Depende: libgdk-pixbuf-2.0-0 (>= 2.22.0) which is a virtual package and is not provided by any available package

 gnome-shell : Depende: libedataserver-1.2-26 (>= 3.33.1) which is a virtual package and is not provided by any available package

               Depende: libgdk-pixbuf-2.0-0 (>= 2.22.0) which is a virtual package and is not provided by any available package

 mesa-vdpau-drivers : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                      Depende: libx11-xcb1 (>= 2:1.7.0) but 2:1.6.12-1ubuntu0.1 is installed
 mesa-vdpau-drivers:i386 : Depende: libc6:i386 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                           Depende: libx11-xcb1:i386 (>= 2:1.7.0) but it is not going to be installed
 mesa-vulkan-drivers : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                       Depende: libx11-xcb1 (>= 2:1.7.0) but 2:1.6.12-1ubuntu0.1 is installed
 mesa-vulkan-drivers:i386 : Depende: libc6:i386 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                            Depende: libx11-xcb1:i386 (>= 2:1.7.0) but it is not going to be installed
 pop-gnome-initial-setup : Depende: libgdk-pixbuf-2.0-0 (>= 2.25.2) which is a virtual package and is not provided by any available package

 pop-upgrade : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
 gnome-terminal : Depende: libvte-2.91-0 (>= 0.62.1) but 0.62.0-1ubuntu1 is installed
 libpop-theme-switcher : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                         Depende: libgdk-pixbuf-2.0-0 (>= 2.22.0) which is a virtual package and is not provided by any available package

 mesa-va-drivers : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                   Depende: libx11-xcb1 (>= 2:1.7.0) but 2:1.6.12-1ubuntu0.1 is installed
 mesa-va-drivers:i386 : Depende: libc6:i386 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                        Depende: libx11-xcb1:i386 (>= 2:1.7.0) but it is not going to be installed
 libglx-mesa0 : Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                Depende: libx11-xcb1 (>= 2:1.7.0) but 2:1.6.12-1ubuntu0.1 is installed
 libglx-mesa0:i386 : Depende: libc6:i386 (>= 2.33) but 2.32-0ubuntu3.2 is installed
                     Depende: libx11-xcb1:i386 (>= 2:1.7.0) but it is not going to be installed

```

**Comment by wellington1993** [comment]
Trying to change some setting in Pop-Shop(Right Screen):

![Captura de tela de 2021-06-10 20-35-20](https://user-images.githubusercontent.com/6920053/121610337-2a2e9600-ca2c-11eb-8a9b-d6e1ff9a92b0.png)

![Captura de tela de 2021-06-10 20-36-27](https://user-images.githubusercontent.com/6920053/121610342-2e5ab380-ca2c-11eb-97ba-2aa0a8df3cce.png)

**Comment by wellington1993** [comment]
Remove groove things in Pop Shop config appears to help:
```
117 pacotes atualizados, 3 novos instalados, 4 a serem removidos e 221 não atualizados.
É preciso obter 127 MB de arquivos. Depois do desempacotamento, 66,1 MB serão liberados.
```

**Comment by wellington1993** [comment]
Some warnings with java packages:

```
dpkg: libridl-java: problemas com dependências, mas mesmo assim a remover conforme você pediu:
 libunoil-java depende de libridl-java.

```
```
dpkg: libridl-java: problemas com dependências, mas mesmo assim a remover conforme você pediu:
 libunoil-java depende de libridl-java.

```

But upgrading packages...

**Comment by wellington1993** [comment]
Many, too many unresolved dependencies problem, maybe critic problem:
https://gist.github.com/wellington1993/cc9519233c2c7fdda76a9813e478f2fa

Probably incorrect resolution with many packages removes, many uninstalls:
https://gist.github.com/wellington1993/93f4806583116cd04847e09a495cfec2

**Comment by wellington1993** [comment]
Probably I can't reboot machine without solve that;

```
Os pacotes a seguir têm dependências desencontradas:
 qemu-system-x86 : Depende: libbrlapi0.8 (>= 6.3+dfsg) mas não é instalável
                   Depende: libc6 (>= 2.33) mas 2.32-0ubuntu3.2 está para ser instalado
                   Depende: libgnutls30 (>= 3.7.0) mas 3.6.15-4ubuntu2.1 está para ser instalado
                   Depende: libpmem1 (>= 1.4) mas não é instalável
                   Depende: libspice-server1 (>= 0.14.2) mas não é instalável
                   Depende: liburing1 (>= 0.7) mas 0.6-3ubuntu1 está para ser instalado
                   Depende: libvirglrenderer1 (>= 0.8.0) mas não é instalável
                   Depende: qemu-system-common (> 1:5.2+dfsg-9ubuntu3~) mas não será instalado
                   Depende: ipxe-qemu-256k-compat-efi-roms mas não é instalável
                   Depende: seabios (>= 1.10.2-1~) mas não é instalável
                   Depende: ipxe-qemu (>= 1.0.0+git-20131111.c3d1e78-1~) mas não é instalável
                   Recomenda: qemu-system-gui (= 1:5.2+dfsg-9ubuntu3) mas não será instalado
 qemu-user : Depende: libc6 (>= 2.33) mas 2.32-0ubuntu3.2 está para ser instalado
             Depende: libgnutls30 (>= 3.7.0) mas 3.6.15-4ubuntu2.1 está para ser instalado
 qemu-user-binfmt : Conflita: qemu-user-static mas 1:5.2+dfsg-9ubuntu3 está para ser instalado
 qemu-user-static : Conflita: qemu-user-binfmt
E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.

```

**Comment by wellington1993** [comment]
When trying to solve unresolved packages:

```
Os pacotes a seguir serão REVERTIDOS:
  appstream-data-pop gnome-online-accounts libfwupd2 libgoa-1.0-0b libgoa-backend-1.0-1 pop-shell-shortcuts popsicle popsicle-gtk
146 pacotes atualizados, 2 pacotes novos instalados, 8 revertidos, 0 a serem removidos e 91 não atualizados.
É preciso baixar 150 MB/152 MB de arquivos.

```
```
Os seguintes pacotes foram instalados automaticamente e já não são necessários:
  libf2fs-format4 libf2fs5
Utilize 'sudo apt autoremove' para os remover.
Os NOVOS pacotes a seguir serão instalados:
  libapksig-java libbpf0

```

Added a custom list in apt with:
```
deb http://deb.debian.org/debian buster-backports main
deb [arch=amd64] http://apt.pop-os.org/staging/master hirsute main
deb [arch=amd64] http://apt.pop-os.org/staging-ubuntu/master hirsute main

```

**Comment by wellington1993** [comment]
Not worked yet. testing with:

```
deb http://deb.debian.org/debian/ unstable main contrib non-free
deb-src http://deb.debian.org/debian/ unstable main contrib non-free

deb http://apt.pop-os.org/staging/master hirsute main contrib non-free
deb http://apt.pop-os.org/staging-ubuntu/master hirsute main contrib non-free

```

**Comment by jacobgkau** [comment]
What commands did you originally use to upgrade? The recommended way to upgrade Pop!_OS is using `pop-upgrade release upgrade`, with `-f` appended to force an upgrade to a beta version like 21.04. (Pop!_OS 21.04 has not been released yet.)

If you still had `groovy` (20.10) sources while running Hirsute (21.04), that would certainly cause package management problems. Typically, `pop-upgrade` should take care of this for you, but if you upgraded manually with a `dist-upgrade` instead of using `pop-upgrade`, then you would have needed to update all of your sources manually. You should also not have any Debian buster/unstable/etc sources added on an Ubuntu-based system like Pop!_OS, so I would recommend removing those.

**Comment by wellington1993** [comment]
@jacobgkau That's the point. 

I used other upgrade commands, like `apt dist upgrade` and `do-release-upgrade`, something like that. 

Could be possible to fix that problems now?
Maybe using `pop-uppgrade`tool?

I'm starting Xorg manually with `startx` because the packages still broken.
And the first Kernel entry in the boot not working, an idea to fix this?

Thanks!

**Comment by wellington1993** [comment]
Still trying to fix dependencies... 

```
The following packages have unmet dependencies:
  mariadb-test: Depende: mariadb-test-data (= 1:10.3.29-0ubuntu0.20.10.1) but 1:10.5.10-0ubuntu0.21.04.1 is to be installed
  libegl-mesa0: Depende: libglapi-mesa (= 21.0.0-1pop0~1616205663~20.10~73b50a1) but 21.0.1-2pop0~1619456815~21.04~bc3b035 is to be installed
  libreoffice-base: Depende: libreoffice-base-core (= 1:7.1.3-0ubuntu0.21.04.1) but 1:7.0.6-0ubuntu0.20.10.1 is to be installed
                    Recomenda: libreoffice-writer but it is not going to be installed
  libgtk-3-0: Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is to be installed
              Recomenda: libgtk-3-bin
  pulseaudio: Depende: libpulse0 (= 1:13.99.2-1ubuntu2.3) but 1:14.2-1ubuntu1.1 is to be installed
  libreoffice-core: Depende: libboost-locale1.74.0 (>= 1.74.0) but it is not installable
                    Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is to be installed
                    Depende: liborcus-0.16-0 but it is not installable
                    Depende: liborcus-parser-0.16-0 but it is not installable
                    Depende: libpoppler107 (>= 21.02.0) but it is not installable
                    Depende: libuno-sal3 (>= 1:7.1.0~alpha1) but 1:7.0.6-0ubuntu0.20.10.1 is to be installed
                    Depende: libx11-xcb1 (>= 2:1.7.0) but 2:1.6.12-1ubuntu0.1 is to be installed
                    Depende: libxmlsec1 (>= 1.2.31) but 1.2.28-2 is to be installed
                    Depende: libxmlsec1-nss (>= 1.2.31) but 1.2.28-2 is to be installed
  samba: Depende: samba-common (= 2:4.12.5+dfsg-3ubuntu4.4) but 2:4.13.3+dfsg-1ubuntu2.1 is to be installed
  libvirt-clients: Depende: libvirt0 (= 6.6.0-1ubuntu3.5) but 7.0.0-2ubuntu2 is to be installed
  gdm3: Depende: gir1.2-gdm-1.0 (= 3.38.1-2ubuntu1.1pop0~1608151004~20.10~a959a69) but 3.38.2.1-3ubuntu1pop1~1623103326~21.04~54de09a is to be installed
        Recomenda: libpam-fprintd (>= 0.8.0-2) but it is not going to be installed
  python3-uno: Depende: libreoffice-core (= 1:7.0.6-0ubuntu0.20.10.1) but 1:7.1.3-0ubuntu0.21.04.1 is to be installed or
                        libreoffice-core-nogui (= 1:7.0.6-0ubuntu0.20.10.1) but it is not going to be installed
  openjdk-11-jre-headless: Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is to be installed
  libmutter-7-0: Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is to be installed
                 Depende: libx11-xcb1 (>= 2:1.7.0) but 2:1.6.12-1ubuntu0.1 is to be installed
  lz4: Depende: liblz4-1 (= 1.9.2-2ubuntu0.20.10.1) but 1.9.3-1ubuntu0.1 is to be installed
  libreoffice-base-core: Depende: libreoffice-core (= 1:7.0.6-0ubuntu0.20.10.1) but 1:7.1.3-0ubuntu0.21.04.1 is to be installed or
                                  libreoffice-core-nogui (= 1:7.0.6-0ubuntu0.20.10.1) but it is not going to be installed
  linux-headers-5.11.0-7614-generic: Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is to be installed
  libpulse0: Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is to be installed
  winbind: Depende: samba-common (= 2:4.12.5+dfsg-3ubuntu4.4) but 2:4.13.3+dfsg-1ubuntu2.1 is to be installed
  libvirt-daemon-driver-qemu: Depende: libvirt-daemon (= 6.6.0-1ubuntu3.5) but 7.0.0-2ubuntu2 is to be installed
  libvirt-daemon-system: Depende: libvirt-daemon (= 6.6.0-1ubuntu3.5) but 7.0.0-2ubuntu2 is to be installed
  systemd-sysv: Depende: systemd (= 247.3-3ubuntu3.1pop1~1623176805~21.04~74cb00e)
  openjdk-11-jre: Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is to be installed
  libnss-winbind: Depende: samba-common (= 2:4.12.5+dfsg-3ubuntu4.4) but 2:4.13.3+dfsg-1ubuntu2.1 is to be installed
  libglx0: Depende: libglx-mesa0 but it is not going to be installed
  xorg: Depende: libgl1-mesa-dri but it is not going to be installed
  samba-common-bin: Depende: samba-common (= 2:4.12.5+dfsg-3ubuntu4.4) but 2:4.13.3+dfsg-1ubuntu2.1 is to be installed
  libvirt0: Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is to be installed
  policykit-1: Depende: libpolkit-agent-1-0 (= 0.105-29ubuntu0.1) but 0.105-30ubuntu0.1 is to be installed
               Depende: libpolkit-gobject-1-0 (= 0.105-29ubuntu0.1) but 0.105-30ubuntu0.1 is to be installed
  fwupd: Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is to be installed
         Depende: libgusb2 (>= 0.3.5) but 0.3.4-0.2 is to be installed
         Depende: libtss2-esys-3.0.2-0 (>= 2.3.1) but it is not installable
  python3-tk: Depende: python3 (>= 3.9.4-0~) but 3.8.6-0ubuntu1 is to be installed
  gnome-shell: Depende: libedataserver-1.2-26 (>= 3.33.1) but it is not installable
  python3-gdbm: Depende: python3 (>= 3.9.4-0~) but 3.8.6-0ubuntu1 is to be installed
  gnome-terminal: Depende: libvte-2.91-0 (>= 0.62.1) but 0.62.0-1ubuntu1 is to be installed
  pulseaudio-utils: Depende: libpulse0 (= 1:13.99.2-1ubuntu2.3) but 1:14.2-1ubuntu1.1 is to be installed
  libglib2.0-0: Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is to be installed
  bind9-libs: Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is to be installed
  libvirt-daemon: Depende: libvirt-daemon-driver-qemu (= 7.0.0-2ubuntu2) but 6.6.0-1ubuntu3.5 is to be installed
                  Depende: libc6 (>= 2.33) but 2.32-0ubuntu3.2 is to be installed
                  Quebra: libvirt-clients (< 6.9.0-2~) but 6.6.0-1ubuntu3.5 is to be installed
                  Quebra: libvirt-daemon-system (< 6.9.0-3~) but 6.6.0-1ubuntu3.5 is to be installed

```

Thanks!

**Comment by wellington1993** [comment]
@jacobgkau I can't use the toll now:

```
pop-os :: ~ » pop-upgrade release upgrade
checking if pop-upgrade requires an update
pop-upgrade: calling UpdateCheck method failed
  caused by: The name com.system76.PopUpgrade was not provided by any .service files
```

Can I fix that manually?

Thanks!

**Comment by mmstick** [comment]
I think you'll resolve this quicker by reinstalling. Using Ubuntu's release upgrade tool is unlikely to work in Pop.

**Comment by wellington1993** [comment]
@mmstick Can you help me to reinstall some important packages?
Like related to the Gnome and login manager?

How to edit the kernel list in the boot?
I think the PopOS are not using the GRUB. 

Thanks!

**Comment by wellington1993** [comment]
Could someone list the cosmic related packages and defualt apt config and sources lists?
I will try to fix some things manually waiting for the official release. 

And if possible, someone could list the no ubuntu packages used by PopOS 21.04 and that versions. 
I will try to reinstall that packages too.

There is a release date of PopOS 21.04?

@mmstick  @jacobgkau 
Thanks!

**Comment by wellington1993** [comment]
Now the biggest problem is how to fix that dependency conflict: 
```

Os pacotes a seguir têm dependências desencontradas:
 libpop-desktop-widget : Depende: libc6 (>= 2.33) mas 2.32-0ubuntu3.2 está para ser instalado
E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.

```

When I try to reinstall gnome-control-center:
`sudo apt install --reinstall gnome-control-center\*`

**Comment by wellington1993** [comment]
Still trying to fix packages:

Fix  broken output:  https://gist.github.com/wellington1993/543f2d73556a8d4628cd448fb9217e5a

```c
pop-os:/tmp:% sudo apt upgrade
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Você pode querer executar 'apt --fix-broken install' para corrigí-los.
Os pacotes a seguir têm dependências desencontradas:
 libc-bin : Depende: libc6 (< 2.33) mas 2.33-0ubuntu5 está instalado
 libc-dev-bin : Depende: libc6 (< 2.33) mas 2.33-0ubuntu5 está instalado
 libc6 : Quebra: fakeroot (< 1.25.3-1.1ubuntu2~) mas 1.25.2-1 está instalado
         Quebra: locales (< 2.33) mas 2.32-0ubuntu3.2 está instalado
         Quebra: locales-all (< 2.33) mas 2.32-0ubuntu3.2 está instalado
         Quebra: locales-all:i386 (< 2.33)
         Quebra: libc6:i386 (!= 2.33-0ubuntu5) mas 2.32-0ubuntu3.2 está instalado
 libc6:i386 : Quebra: libc6 (!= 2.32-0ubuntu3.2) mas 2.33-0ubuntu5 está instalado
 libc6-dbg : Depende: libc6 (= 2.32-0ubuntu3.2) mas 2.33-0ubuntu5 está instalado
 libc6-dev : Depende: libc6 (= 2.32-0ubuntu3.2) mas 2.33-0ubuntu5 está instalado
 libc6-i386 : Depende: libc6 (= 2.32-0ubuntu3.2) mas 2.33-0ubuntu5 está instalado
 libc6-x32 : Depende: libc6 (= 2.32-0ubuntu3.2) mas 2.33-0ubuntu5 está instalado
E: Dependências desencontradas. Tente 'apt --fix-broken install' sem nenhum pacote (ou especifique uma solução).
```

**Comment by wellington1993** [comment]
Still trying to fix the packages, unsuccessfully:

https://gist.github.com/wellington1993/740a0c3e0aca7989bf14c9fadf99b622

**Comment by wellington1993** [comment]
Appears to be needed to remove: https://gist.github.com/wellington1993/12a36dda2abc18c92c4707c13fd824a8#file-asked-to-remove-in-every-apt-use-popos-21-04-upgrade-txt

Any of that packages are really really necessary for PopOS? 

Thanks!

**Comment by wellington1993** [comment]
Trying to use other desktop environments:
https://gist.github.com/wellington1993/a679e595d955db812cc614453b18bc58

I cant configure the docker in the PopOS 21.04 desktop. 
The config windows closes when I try to change the docker to auto-hide.

Thanks!

**Comment by wellington1993** [comment]
After some upgrades: https://gist.github.com/wellington1993/46d322682263b960b1fe722c410f7b0f

Thanks!

**Comment by wellington1993** [comment]
Maybe that issue is related to: https://github.com/pop-os/cosmic/issues/78

**Comment by wellington1993** [comment]
Can`t update that packages, the upgrade or dist upgrade commands run, but if I try to run again, the same result, asking to update the same packages, are returned every time:

```
wellington@pop-os:~/Documents/upgrade/help 
 $ DEBIAN_FRONTEND=noninteractive sudo apt dist-upgrade -y --ignore-missing --allow-downgrades
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
Calculando atualização... Pronto
Os seguintes pacotes foram instalados automaticamente e já não são necessários:
  libboost-filesystem1.71.0 libboost-iostreams1.71.0 libboost-log1.71.0 libboost-program-options1.71.0 libboost-regex1.71.0 libboost-thread1.71.0
  libcrypto++6 libdirectfb-1.7-7 libedataserver-1.2-25 libedataserverui-1.2-2 libfilezilla0 libgeos-3.8.1 libjemalloc2 libkyotocabinet16v5
  libllvm10 libpgm-5.2-0 libpython3.8 libraw19 libreadline5 librpm8 librpmio8 libsane libtsk13 libwireshark13 libwiretap10 libwsutil11
  libxalan-c111 php-doctrine-inflector php-doctrine-reflection printer-driver-hpijs
Utilize 'sudo apt autoremove' para os remover.
Os pacotes a seguir serão REVERTIDOS:
  alacritty appstream-data-pop firmware-manager-notify fwupd gdm3 gnome-online-accounts gnome-shell ibus-mozc libfirmware-manager libfwupd2
  libfwupdplugin1 libgoa-1.0-0b libgoa-backend-1.0-1 libmutter-7-0 libpop-desktop-widget libpop-theme-switcher libpop-upgrade-gtk
  libs76-hidpi-widget mozc-server pop-shell-shortcuts pop-shop pop-upgrade popsicle popsicle-gtk system76-power ubuntu-drivers-common
0 pacotes atualizados, 0 pacotes novos instalados, 26 revertidos, 0 a serem removidos e 0 não atualizados.
É preciso baixar 1.967 kB/29,2 MB de arquivos.
Depois desta operação, 0 B adicionais de espaço em disco serão usados.

```

@mmstick @jacobgkau  Thanks!

**Comment by wellington1993** [comment]
After `autoremove`, result of dist-upgrade try:

```
 $ DEBIAN_FRONTEND=noninteractive sudo apt dist-upgrade -y --ignore-missing --allow-downgrades
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
Calculando atualização... Pronto
Os pacotes a seguir serão REVERTIDOS:
  alacritty appstream-data-pop firmware-manager-notify fwupd gdm3 gnome-online-accounts gnome-shell ibus-mozc libfirmware-manager libfwupd2
  libfwupdplugin1 libgoa-1.0-0b libgoa-backend-1.0-1 libmutter-7-0 libpop-desktop-widget libpop-theme-switcher libpop-upgrade-gtk
  libs76-hidpi-widget mozc-server pop-shell-shortcuts pop-shop pop-upgrade popsicle popsicle-gtk system76-power ubuntu-drivers-common
0 pacotes atualizados, 0 pacotes novos instalados, 26 revertidos, 0 a serem removidos e 0 não atualizados.
É preciso baixar 0 B/29,2 MB de arquivos.
Depois desta operação, 0 B adicionais de espaço em disco serão usados.
apt-listdifferences: fetching source packages: ubuntu-drivers-common:amd64 firmware-manager-notify:amd64 libfwupd2:amd64 libfwupdplugin1:amd64 fwupd:amd64 libmutter-7-0:amd64 gnome-shell:amd64 gdm3:amd64 libfirmware-manager:amd64 libgoa-1.0-0b:amd64 libgoa-backend-1.0-1:amd64 libpop-desktop-widget:amd64 libpop-theme-switcher:amd64 pop-upgrade:amd64 libpop-upgrade-gtk:amd64 libs76-hidpi-widget:amd64 pop-shell-shortcuts:amd64 system76-power:amd64 alacritty:amd64 appstream-data-pop:all gnome-online-accounts:amd64 mozc-server:amd64 ibus-mozc:amd64 popsicle:amd64 popsicle-gtk:amd64 pop-shop:amd6
```

**Comment by wellington1993** [comment]
After comment all non `hirsute` sources:

```c
└─[$]> sudo apt upgrade 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
Calculando atualização... Pronto
Os pacotes a seguir serão REVERTIDOS:
  alacritty appstream-data-pop firmware-manager-notify fwupd gdm3 gnome-online-accounts gnome-shell ibus-mozc libfirmware-manager libfwupd2
  libfwupdplugin1 libgoa-1.0-0b libgoa-backend-1.0-1 libmutter-7-0 libpop-desktop-widget libpop-theme-switcher libpop-upgrade-gtk
  libs76-hidpi-widget mozc-server pop-shell-shortcuts pop-shop pop-upgrade popsicle popsicle-gtk system76-power ubuntu-drivers-common
0 pacotes atualizados, 0 pacotes novos instalados, 26 revertidos, 0 a serem removidos e 0 não atualizados.
É preciso baixar 0 B/29,2 MB de arquivos.
Depois desta operação, 0 B adicionais de espaço em disco serão usados.
Você quer continuar? [S/n] 

```
Appears to be a loop, upgrading and downgrading the same packages, downgrading when `apt upgrade` and upgrading when `apt dist-upgrade` and vice-versa. 

And the packages appears to be PopOS direct related. 

Thanks! @mmstick @jacobgkau

**Comment by wellington1993** [comment]
**APT files:** [apt.zip](https://github.com/pop-os/pop/files/6719052/apt.zip)

My APT files if help.

Thanks!

**Comment by wellington1993** [comment]
@mmstick @jacobgkau @aral @burden 

**New apt:** 
[apt.zip](https://github.com/pop-os/cosmic/files/6723061/apt.zip)

100% fine the packages and sources.
And about Cosmic... 90% but I think is not related to the packages directly...

Thanks so much @DuttaAB-dev!
