### ISSUE TITLE
The app Hiri when installed as a Snap will not run on Pop OS [18.04]

### ISSUE THREAD

**Issue by Iiari** [pop-os/pop#176]
Pop OS 18.04 beta

When I install the email app Hiri via snap on 18.04 it installs but will not run.  When I install it on Budgie 18.04, it runs without difficulty.  Interestingly, it wouldn't run in Pop OS 17.10 either, so this may be a Pop thing.  Here is the output from "snap run hiri":

Error in sys.excepthook:
Traceback (most recent call last):
  File "hiriapp.py", line 276, in <module>
  File "hiri/services/mixpanel.py", line 34, in __init__
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/ubuntu/.virtualenvs/hiri/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/distro.py", line 1074, in <module>
  File "site-packages/distro.py", line 594, in __init__
  File "site-packages/distro.py", line 846, in _get_os_release_info
PermissionError: [Errno 13] Permission denied: '/etc/os-release'

Original exception was:
Traceback (most recent call last):
  File "hiriapp.py", line 276, in <module>
  File "hiri/services/mixpanel.py", line 34, in __init__
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/ubuntu/.virtualenvs/hiri/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/distro.py", line 1074, in <module>
  File "site-packages/distro.py", line 594, in __init__
  File "site-packages/distro.py", line 846, in _get_os_release_info
PermissionError: [Errno 13] Permission denied: '/etc/os-release'
[8405] Failed to execute script hiriapp

**Comment by Matakaheru** [comment]
Will have to boot VM and look, but does Pop!_OS have a file called
/etc/os-release? The error makes it look like they have named it something
else. Either that or the file has no read bits. Chmod it +r if exists and
see if that helps. The app wants to know what OS you are on and it can't so
stops.

**Comment by Matakaheru** [comment]
Alright, booted my VM and /etc/os-release is a link to
/etc/pop-os/os-release which does have world readable bit set. So it may be
that the Python scripts the app is running does not like following links.
Remove the link in /etc and copy the file up to test.
