### ISSUE TITLE
Error keeps on repeating.

### ISSUE THREAD

**Issue by thekingisherenow** [pop-os/pop#2638]
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]: Unhandled Error
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]: Traceback (most recent call last):
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:   File "/usr/lib/python3/dist-packages/deluge/ui/gtk3/gtkui.py", line 246, in start
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:     reactor.run()
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:   File "/usr/lib/python3/dist-packages/twisted/internet/_glibbase.py", line 277, in run
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:     self._run()
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:   File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1689, in main
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:     return _Gtk_main(*args, **kwargs)
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:   File "/usr/lib/python3/dist-packages/twisted/internet/_glibbase.py", line 308, in _simulate
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:     self.runUntilCurrent()
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]: --- <exception caught here> ---
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:   File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 991, in runUntilCurrent
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:     call.func(*call.args, **call.kw)
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:   File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 345, in _on_alert_session_stats
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:     self._update_session_cache_hit_ratio()
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:   File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 361, in _update_session_cache_hit_ratio
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]:     self.session_status['disk.num_blocks_cache_hits'] / blocks_read
Oct  6 14:30:52 pop-os google-chrome.desktop[16149]: builtins.KeyError: 'disk.num_blocks_cache_hits'
Oct  6 14:30:52 pop-os google-chrome.desktop[16148]: 14:30:52 [CRITICAL][twisted                           :147 ] Unhandled Error
Oct  6 14:30:52 pop-os google-chrome.desktop[16148]: Traceback (most recent call last):

**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by gavinlaking** [comment]
This is part of the `deluge` package, the fix is here: https://github.com/deluge-torrent/deluge/commit/89189adb24321c3db6bfa816ec557d7d8367ba24

I'm not sure if this has been released yet.
