### ISSUE TITLE
Can't update initramfs-tools

### ISSUE THREAD

**Issue by martinspudich** [pop-os/pop#3156]
**Distribution (run `cat /etc/os-release`):**
 > cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
initramfs-tools

**Issue/Bug Description:**
When updating system with `apt update & apt upgrade` the update of package  `initramfs-tools` fails with error code 1

From apt upgrade log I see error:

ModuleNotFoundError: No module named 'debian'

Full log of apt upgrade:

```
 sudo apt upgrade
Načítají se seznamy balíků… Hotovo
Vytváří se strom závislostí… Hotovo
Načítají se stavové informace… Hotovo
Propočítává se aktualizace… Hotovo
0 aktualizováno, 0 nově instalováno, 0 k odstranění a 0 neaktualizováno.
1 instalováno nebo odstraněno pouze částečně.
Po této operaci bude na disku použito dalších 0 B.
Chcete pokračovat? [Y/n] y
Nastavuje se balík initramfs-tools (0.140ubuntu13.4) …
update-initramfs: deferring update (trigger activated)
Zpracovávají se spouštěče pro balík initramfs-tools (0.140ubuntu13.4) …
update-initramfs: Generating /boot/initrd.img-6.5.4-76060504-generic
Traceback (most recent call last):
  File "/usr/bin/kernelstub", line 44, in <module>
    from kernelstub import application
  File "/usr/lib/python3/dist-packages/kernelstub/application.py", line 59, in <module>
    from . import kernel_option as KernelOption
  File "/usr/lib/python3/dist-packages/kernelstub/kernel_option.py", line 3, in <module>
    from debian.changelog import Version
ModuleNotFoundError: No module named 'debian'
run-parts: /etc/initramfs/post-update.d//zz-kernelstub exited with return code 1
dpkg: chyba při zpracovávání balíku initramfs-tools (--configure):
 podproces skript z instalovaného balíku initramfs-tools: post-installation vrátil chybový návratový stav 1
Při zpracování nastaly chyby:
 initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Expected behavior:**

Upgrading with apt upgrade without any errors.

**Comment by martinspudich** [comment]
Can anyone help me with this issue?

I am not able to update the kernel now, I think it is because of the initramfs-tools issue.

```
sudo apt upgrade
Načítají se seznamy balíků… Hotovo
Vytváří se strom závislostí… Hotovo
Načítají se stavové informace… Hotovo
Propočítává se aktualizace… Hotovo
0 aktualizováno, 0 nově instalováno, 0 k odstranění a 0 neaktualizováno.
2 instalováno nebo odstraněno pouze částečně.
Po této operaci bude na disku použito dalších 0 B.
Chcete pokračovat? [Y/n] y
Nastavuje se balík linux-image-6.5.6-76060506-generic (6.5.6-76060506.202310061235~1697396945~22.04~9283e32) …
Nastavuje se balík initramfs-tools (0.140ubuntu13.4) …
update-initramfs: deferring update (trigger activated)
Zpracovávají se spouštěče pro balík linux-image-6.5.6-76060506-generic (6.5.6-76060506.202310061235~1697396945~22.04~9283e32) …
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 6.5.6-76060506-generic
   ...done.
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-6.5.6-76060506-generic
Traceback (most recent call last):
  File "/usr/bin/kernelstub", line 44, in <module>
    from kernelstub import application
  File "/usr/lib/python3/dist-packages/kernelstub/application.py", line 59, in <module>
    from . import kernel_option as KernelOption
  File "/usr/lib/python3/dist-packages/kernelstub/kernel_option.py", line 3, in <module>
    from debian.changelog import Version
ModuleNotFoundError: No module named 'debian'
run-parts: /etc/initramfs/post-update.d//zz-kernelstub exited with return code 1
run-parts: /etc/kernel/postinst.d/initramfs-tools exited with return code 1
dpkg: chyba při zpracovávání balíku linux-image-6.5.6-76060506-generic (--configure):
 podproces skript z instalovaného balíku linux-image-6.5.6-76060506-generic: post-installation vrátil chybový návratový stav 1
Zpracovávají se spouštěče pro balík initramfs-tools (0.140ubuntu13.4) …
update-initramfs: Generating /boot/initrd.img-6.5.6-76060506-generic
Traceback (most recent call last):
  File "/usr/bin/kernelstub", line 44, in <module>
    from kernelstub import application
  File "/usr/lib/python3/dist-packages/kernelstub/application.py", line 59, in <module>
    from . import kernel_option as KernelOption
  File "/usr/lib/python3/dist-packages/kernelstub/kernel_option.py", line 3, in <module>
    from debian.changelog import Version
ModuleNotFoundError: No module named 'debian'
run-parts: /etc/initramfs/post-update.d//zz-kernelstub exited with return code 1
dpkg: chyba při zpracovávání balíku initramfs-tools (--configure):
 podproces skript z instalovaného balíku initramfs-tools: post-installation vrátil chybový návratový stav 1
Při zpracování nastaly chyby:
 linux-image-6.5.6-76060506-generic
 initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by martinspudich** [comment]
I solved it today in the evening by reinstalling python3-debina package with command sudo `apt install --reinstall python3-debian`

**Comment by nccurry** [comment]
The following was needed for me on PopOS 22.04. 
`sudo apt install --reinstall python3-debian python3-repolib`
