### ISSUE TITLE
Missing dependency for gitkraken

### ISSUE THREAD

**Issue by pierredavidbelanger** [pop-os/pop#324]
**Distribution (run `cat /etc/os-release`):**
 
```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
$ apt policy gitkraken
gitkraken:
  Installed: 3.6.6
  Candidate: 3.6.6
  Version table:
 *** 3.6.6 500
        500 http://apt.pop-os.org/proprietary bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

```
$ gitkraken 
Node started time: 1532127010389
libgnome-keyring.so.0: cannot open shared object file: No such file or directory
Error: libgnome-keyring.so.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/gitkraken/resources/app.asar/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/usr/share/gitkraken/resources/app.asar/node_modules/keytar/lib/keytar.js:58:4)
```

**Steps to reproduce (if you know):**

Install the package (with synaptic, but I guess that is not the issue) and run it.

**Other Notes:**

Obviously `apt install libgnome-keyring0` fixes the issue.

**Comment by mmstick** [comment]
I'll report this to upstream, since we don't package it.
