### ISSUE TITLE
Kernel panic - not syncing: No working init found.

### ISSUE THREAD

**Issue by PS1TD** [pop-os/pop#3412]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 ```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Kernel panic after latest sudo apt upgrade

**Steps to reproduce (if you know):**
Happens on PC restart

**Expected behavior:**

**Other Notes:**
The solution is to try to restart PC multiple times until it successfully boots up.
I have no idea what is causing this error I have tried everything to fix it.
Including using a recovery usb stick to reinstall PoP_OS.
Surprisingly the usb recovery stick was having the same issue.
I suspect it might be something broken in the kernel itself.
![20241202_202147](https://github.com/user-attachments/assets/d2f7ad8e-ea78-41a5-bbf5-d6c32b67fe0e)

**Comment by galaczi** [comment]
This happens on my PC too. It's PopOS specific, since I used to run Linux Mint and it never happened. Switched back to Pop and it started happening again.

During an apt upgrade I am seeing these errors:

```

Processing triggers for initramfs-tools (0.140ubuntu13.5pop0~1750449265~22.04~45b6e64) ...
update-initramfs: Generating /boot/initrd.img-6.12.10-76061203-generic
cryptsetup: ERROR: Couldn't resolve device 
    UUID=0d056f7f-a72b-4332-a1f3-e4a2c6fbbd90
W: Possible missing firmware /lib/firmware/amdgpu/ip_discovery.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vega10_cap.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/sienna_cichlid_cap.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/navi12_cap.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_cap.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/gc_11_0_0_toc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/gc_11_0_3_mes.bin for module amdgpu
W: initramfs-tools configuration sets RESUME=UUID=0d056f7f-a72b-4332-a1f3-e4a2c6fbbd90
W: but no matching swap device is available.
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for libc-bin (2.35-0ubuntu3.10) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for dbus (1.12.20-2ubuntu4.1) ...
Processing triggers for shared-mime-info (2.1-2) ...
Processing triggers for dbus-broker (29-4build1) ...
Processing triggers for linux-image-6.12.10-76061203-generic (6.12.10-76061203.202412060638~1
753385872~22.04~dc2e00d) ...
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 6.12.10-76061203-generic
   ...done.
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-6.12.10-76061203-generic
cryptsetup: ERROR: Couldn't resolve device 
    UUID=0d056f7f-a72b-4332-a1f3-e4a2c6fbbd90
W: Possible missing firmware /lib/firmware/amdgpu/ip_discovery.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vega10_cap.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/sienna_cichlid_cap.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/navi12_cap.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_cap.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/gc_11_0_0_toc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/gc_11_0_3_mes.bin for module amdgpu
W: initramfs-tools configuration sets RESUME=UUID=0d056f7f-a72b-4332-a1f3-e4a2c6fbbd90
W: but no matching swap device is available.
/etc/kernel/postinst.d/zz-update-grub:
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-6.12.10-76061203-generic
Found initrd image: /boot/initrd.img-6.12.10-76061203-generic
Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.
```

**Comment by kszyho8** [comment]
I also encounter kernel panic screen, and multiple restarts didn't resolve it.

What I did to fix:
1) boot into live USB or use recovery partition
1) Chroot into existing operating system using this guide (start at Repair step, stop before After Chroot): [Pop Recovery](https://support.system76.com/articles/pop-recovery)
1) Once you execute `sudo chroot /mnt` and see something like `root@pop-os#` you can run scripts on your system
1) run `update-initramfs -u -k all` - it can take some time
1) reboot

For me rebuilding init was enough, but if the problem still persists I found that can be faulty RAM or hard drive.

**Comment by ldalorion** [comment]
I hit this issue as well and followed @kszyho8's recommendation. However, `update-initramfs -u -k all` kept faililng. My recovery partition was full from a previous upgrade: 
```
OSError: [Errno 28] No space left on device: '/boot/initrd.img-7.0.11-76070011-generic' -> '/boot/efi/EFI/Pop_OS-4f4533ba-6d30-4a27-8b12-487199782083/initrd.img'
```
Then I had to figure out why the new install file was malformed (no UUID) after retrying `update-initramfs -u -k all` . 
```
ls /boot/efi/EFI/ 
BOOT Linux Pop_OS- Recovery-D363-C2E2 systemd
```
After some stumbing around, we (Claude and I) discovered that the `/mnt` for loop in ithe docs needed to include `dev/` to the list of mounts. 
```
for i in dev dev/pts proc sys run; do sudo mount -R /$i /mnt/$i; done
for i in dev [dev/] dev/pts proc sys run; do sudo mount -R /$i /mnt/$i; done
```

After that I was able to execute `update-initramfs -u -k all`  without any errors, restart, and move on with my life. 😂

**Comment by kfili** [comment]
Thanks all for the helpful posts so far.

@ldalorion I also got the "No space" error. I'm getting stuck trying to use the solutions, can you/someone please help? 

Below i tried the commands that @kszyho8 posted, including the [Pop-Recovery article](https://system76.com/support/pop-recovery). The The final Chroot command from this article seems to work, but `update-initramfs -u -k all` still returns "No space" error. And I'm not sure how to adapt @ldalorion 's commands to my situation, or what i need to do.

note that i booted ubuntu from a usb stick on the laptop which is having trouble booting Pop-OS 24.04. Trouble started after an update.

running chroot and update-initramfs:
```
ubuntu@ubuntu:~$ for i in /dev /dev/pts /proc /sys /run; do sudo mount -R $i /mnt$i; done
sudo chroot /mnt
mount: /mnt/dev: mount() failed: No space left on device.
       dmesg(1) may have more information after failed mount system call.
mount: /mnt/dev/pts: mount() failed: No space left on device.
       dmesg(1) may have more information after failed mount system call.

root@ubuntu:/# update-initramfs -u -k all
update-initramfs: Generating /boot/initrd.img-7.1.5-76070105-generic
W: plymouth module (/usr/lib/x86_64-linux-gnu/plymouth//ubuntu-text.so) missing, skipping that theme.
kernelstub.Config    : INFO     Looking for configuration...
kernelstub           : INFO     System information: 

    OS:..................Pop!_OS 24.04
    Root partition:....../dev/dm-1
    Root FS UUID:........d885ea2e-8bea-4207-9adc-015be653bf03
    ESP Path:............/boot/efi
    ESP Partition:......./dev/nvme0n1p1
    ESP Partition #:.....1
    NVRAM entry #:.......-1
    Boot Variable #:.....0000
    Kernel Boot Options:.quiet loglevel=0 systemd.show_status=false splash intel_iommu=off
    Kernel Image Path:.../boot/vmlinuz-7.1.5-76070105-generic
    Initrd Image Path:.../boot/initrd.img-7.1.5-76070105-generic
    Force-overwrite:.....False

kernelstub.Installer : INFO     Copying Kernel into ESP
kernelstub.Installer : INFO     Copying initrd.img into ESP
kernelstub.Installer : ERROR    Couldn't copy the initrd onto the ESP!
This is a critical error and we cannot continue. Check your settings to see if there is a typo. Otherwise, check permissions and try again.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kernelstub/installer.py", line 278, in copy_files
    shutil.copy(src, dest)
  File "/usr/lib/python3.12/shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.12/shutil.py", line 273, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.12/shutil.py", line 164, in _fastcopy_sendfile
    raise err from None
  File "/usr/lib/python3.12/shutil.py", line 150, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device: '/boot/initrd.img-7.1.5-76070105-generic' -> '/boot/efi/EFI/Pop_OS-d885ea2e-8bea-4207-9adc-015be653bf03/initrd.img'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kernelstub/installer.py", line 144, in setup_kernel
    self.copy_files(
  File "/usr/lib/python3/dist-packages/kernelstub/installer.py", line 282, in copy_files
    raise FileOpsError("Could not copy one or more files.")
kernelstub.installer.FileOpsError: Could not copy one or more files.
run-parts: /etc/initramfs/post-update.d//zz-kernelstub exited with return code 171

root@ubuntu:/# exit
```

running @ldalorion 's commands:
```
ubuntu@ubuntu:~$ for i in dev dev/pts proc sys run; do sudo mount -R /$i /mnt/$i; done
mount: /mnt/dev: mount() failed: No space left on device.
       dmesg(1) may have more information after failed mount system call.
mount: /mnt/dev/pts: mount() failed: No space left on device.
       dmesg(1) may have more information after failed mount system call.
mount: /mnt/proc: mount() failed: No space left on device.
       dmesg(1) may have more information after failed mount system call.
mount: /mnt/sys: mount() failed: No space left on device.
       dmesg(1) may have more information after failed mount system call.
mount: /mnt/run: mount() failed: No space left on device.
       dmesg(1) may have more information after failed mount system call.

ubuntu@ubuntu:~$ 
for i in dev [dev/] dev/pts proc sys run; do sudo mount -R /$i /mnt/$i; done
mount: /mnt/dev: mount() failed: No space left on device.
       dmesg(1) may have more information after failed mount system call.
mount: /mnt/[dev/]: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
mount: /mnt/dev/pts: mount() failed: No space left on device.
       dmesg(1) may have more information after failed mount system call.
mount: /mnt/proc: mount() failed: No space left on device.
       dmesg(1) may have more information after failed mount system call.
mount: /mnt/sys: mount() failed: No space left on device.
       dmesg(1) may have more information after failed mount system call.
mount: /mnt/run: mount() failed: No space left on device.
       dmesg(1) may have more information after failed mount system call.


```
